name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Netlify
        uses: netlify/actions-cli@v2.1.0
        with:
          command: deploy
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
